platform :ios, '7.0'
link_with ['RadarcOnlineSDK']

source 'https://github.com/CocoaPods/Specs.git'

target 'RadarcOnlineSDK' do
  pod 'AFNetworking', '2.5.3', :inhibit_warnings => true
  pod 'SVProgressHUD', '1.1.3', :inhibit_warnings => true
  pod 'ECSlidingViewController', '2.0.3', :inhibit_warnings => true
  pod 'XMLDictionary', '1.4', :inhibit_warnings => true
  pod 'SVPullToRefresh', '0.4.1', :inhibit_warnings => true
  pod 'Colours', '5.6.2', :inhibit_warnings => true
  pod 'NSUserDefaults-AESEncryptor', '0.0.4', :inhibit_warnings => true
  pod 'CorePlot', '1.5.1', :inhibit_warnings => true
  pod 'DCKeyValueObjectMapping', '1.4', :inhibit_warnings => true
  pod 'SDWebImage', '3.7.2', :inhibit_warnings => true
  pod 'UIActivityIndicator-for-SDWebImage', '1.2', :inhibit_warnings => true
  pod 'ActionSheetPicker-3.0', '1.6.2', :inhibit_warnings => true
end

post_install do |installer_representation|
 
  # Overrride OTHER_LDFLAGS to fix any problems with the CocoaPods installation 
  workDir = Dir.pwd

  xcconfigDebug = "#{workDir}/Pods/Target Support Files/Pods-RadarcOnlineSDK/Pods-RadarcOnlineSDK.debug.xcconfig"
  xcconfig = File.read(xcconfigDebug)
  newXcconfig = xcconfig.gsub(/OTHER_LDFLAGS = [A-Z_ =\-a-z\"0-9]*/, "OTHER_LDFLAGS = $(inherited) ")
  File.open(xcconfigDebug, "w") { |file| file << newXcconfig }

  xcconfigRelease = "#{workDir}/Pods/Target Support Files/Pods-RadarcOnlineSDK/Pods-RadarcOnlineSDK.release.xcconfig"
  xcconfig = File.read(xcconfigRelease)
  newXcconfig = xcconfig.gsub(/OTHER_LDFLAGS = [A-Z_ =\-a-z\"0-9]*/, "OTHER_LDFLAGS = $(inherited) ")
  File.open(xcconfigRelease, "w") { |file| file << newXcconfig }
  
  # Build all archs for debug config
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "$(ARCHS_STANDARD_INCLUDING_64_BIT)"
      config.build_settings['VALID_ARCHS'] = "$(ARCHS_STANDARD_INCLUDING_64_BIT)"
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end

end